[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
version = "0.0.1"
name = "stadcal"
dependencies = [
    "apscheduler",
    "flask",
    "gunicorn",
    "icalendar",
]
requires-python = ">=3.13"
